const assert = require('node:assert/strict');
const { test, beforeEach } = require('node:test');
const Module = require('node:module');
const fs = require('node:fs');
const path = require('node:path');
const ts = require('typescript');
const root = path.resolve(__dirname, '..');
const originalLoad = Module._load;
const originalResolve = Module._resolveFilename;
const sent = new Map();
let rejectRecipient = '';
Module._resolveFilename = function (name, parent, ...args) { return originalResolve.call(this, name.startsWith('@/') ? path.join(root, name.slice(2)) : name, parent, ...args); };
Module._extensions['.ts'] = (module, filename) => { const output = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true } }); module._compile(output.outputText, filename); };
Module._load = function (name, parent, main) {
  if (name === 'resend') return { Resend: class { emails = { send: async (payload, options) => { if (payload.to === rejectRecipient) return { error: { name: 'application_error' }, data: null }; const key = options.idempotencyKey; const existing = sent.get(key); if (existing && JSON.stringify(existing.payload) !== JSON.stringify(payload)) return { error: { name: 'invalid_idempotency_key' }, data: null }; if (!existing) sent.set(key, { payload, id: `email-${sent.size + 1}` }); return { error: null, data: { id: sent.get(key).id } }; } }; } };
  return originalLoad.call(this, name, parent, main);
};
Object.assign(process.env, { VERCEL_ENV: 'preview', PILOT_SIGNING_SECRET: 'qa-only-32-byte-secret-not-a-live-credential', RESEND_API_KEY: 'qa-fake-key', CONTACT_FROM_EMAIL: 'OMNeXa <noreply@omnexagoc.com>', NEXT_PUBLIC_RECAPTCHA_SITE_KEY: 'qa-site', RECAPTCHA_PROJECT_ID: 'qa-project', RECAPTCHA_ENTERPRISE_API_KEY: 'qa-key' });
global.fetch = async (_url, options) => ({ ok: true, json: async () => ({ tokenProperties: { valid: JSON.parse(options.body).event.token === 'qa-valid-captcha', hostname: 'localhost' } }) });
const applyRoute = require('../app/api/pilot/apply/route.ts');
const { validatePilotApplication } = require('../lib/pilot-validation.ts');
const { pilotProducts } = require('../lib/pilot-catalog.ts');
const { PILOT_AGREEMENT_VERSION } = require('../lib/pilot-agreement.ts');
const request = (body, overrides = {}) => new Request('https://preview.example/api/pilot/apply', { method: 'POST', headers: { origin: 'https://preview.example', 'content-type': 'application/json', 'x-forwarded-for': '192.0.2.10', ...overrides }, body: JSON.stringify(body) });
const draft = (slug = 'human-machine-sadhana') => { const product = pilotProducts.find(p => p.slug === slug); return { productSlug: slug, initiativeSlug: product.initiativeSlug, fullName: 'Preview Test Applicant', email: 'pilot-test@example.com', country: 'Singapore', organisation: product.audience === 'B2B' ? 'Preview Test Organisation' : '', role: 'Preview evaluator', experienceLevel: 'Personal or lived experience', experience: 'I have relevant everyday experience and would like to provide structured feedback.', goals: 'I would test clarity, accessibility and the overall user experience.', availability: '1–2 hours per week' }; };
const signed = (slug, extra = {}) => ({ application: draft(slug), captchaToken: 'qa-valid-captcha', signature: 'Preview Test Applicant', signatureActionTime: new Date().toISOString(), agreementVersion: PILOT_AGREEMENT_VERSION, ndaConsent: true, privacyConsent: true, adultConsent: true, benefitConsent: true, authorityConsent: true, ...extra });
beforeEach(() => { sent.clear(); rejectRecipient = ''; global.__omnexaPilotLimits?.clear(); process.env.VERCEL_ENV = 'preview'; });

test('all 12 products classify explicitly; 7 B2C and 5 B2B', () => { assert.equal(pilotProducts.length, 12); assert.equal(pilotProducts.filter(p => p.audience === 'B2C').length, 7); assert.equal(pilotProducts.filter(p => p.audience === 'B2B').length, 5); pilotProducts.forEach(p => assert.equal(validatePilotApplication(draft(p.slug)).productSlug, p.slug)); });
test('validation rejects unlisted products, mismatched initiatives and missing B2B organisation', () => { for (const change of [{ productSlug: 'unknown' }, { initiativeSlug: 'wrong' }, { email: 'bad\nemail@example.com' }, { experience: 'short' }, { availability: 'arbitrary' }]) assert.throws(() => validatePilotApplication({ ...draft(), ...change })); assert.throws(() => validatePilotApplication({ ...draft('nexaaml'), organisation: '' })); });
test('submission requires same-origin JSON, consent, reCAPTCHA and a valid signature', async () => { assert.equal((await applyRoute.POST(request(signed('human-machine-sadhana', { captchaToken: 'bad' })))).status, 400); assert.equal((await applyRoute.POST(request(signed('human-machine-sadhana', { ndaConsent: false })))).status, 400); assert.equal((await applyRoute.POST(request(signed('human-machine-sadhana', { signature: 'Someone Else' })))).status, 400); assert.equal((await applyRoute.POST(request(signed('human-machine-sadhana', { agreementVersion: 'old' })))).status, 409); assert.equal((await applyRoute.POST(request(signed('human-machine-sadhana'), { origin: 'https://other.example' }))).status, 403); });
test('B2C sends exactly one support email with benefit and agreement attachments', async () => { const response = await applyRoute.POST(request(signed('human-machine-sadhana'))); assert.equal(response.status, 200); const result = await response.json(); assert.equal(result.preview, true); assert.equal(sent.size, 1); const support = [...sent.values()][0].payload; assert.equal(support.to, 'support@omnexagoc.com'); assert.ok(support.subject.includes('Pilot interest')); assert.ok(support.text.includes('12 consecutive months')); assert.equal(support.attachments.length, 2); assert.ok(Buffer.from(support.attachments[0].content, 'base64').toString().includes('PREVIEW TEST')); assert.equal(result.agreementCopy.length > 100, true); });
test('B2B support message excludes the individual free subscription offer', async () => { const response = await applyRoute.POST(request(signed('nexaforge'))); assert.equal(response.status, 200); const support = [...sent.values()][0].payload; assert.ok(support.text.includes('one-year free individual subscription offer does not apply')); assert.equal(sent.size, 1); });
test('support delivery failure is returned and no applicant email is attempted', async () => { rejectRecipient = 'support@omnexagoc.com'; const response = await applyRoute.POST(request(signed('human-machine-sadhana'))); assert.equal(response.status, 502); assert.equal(sent.size, 0); });
